### ISSUE TITLE
Testing `inituser` fails the second time showing `exit_code != 0`

### ISSUE THREAD

**Issue by erwagasore** [pindo-io/pindo#26]
<img width="834" alt="screen shot 2018-10-12 at 11 16 37" src="https://user-images.githubusercontent.com/1290048/46860261-57a48b00-ce10-11e8-831b-045ce3a7f3c7.png">
This morning I pulled the latest changes with the intention to start writing `README` for this repo. Unfortunately, I found out that the test for `inituser` works once and other times it fails.

**Comment by erwagasore** [comment]
Investigating the issue found out that the `users` created using `inituser` was being saved in the normal database instead of the testing database. This was the cause of test passing on a fresh database but cannot run it twice and succeed.

This can be miss-leading since the CI cannot show such an error because everytime it builds new database

**Comment by kenessajr** [comment]
Yeah, I think once we add the first user from the test we need to delete him directly. This will help handling this error.

**Comment by erwagasore** [comment]
But that is not the real-life behavior of the application. I am fixing it the right way.
