### ISSUE TITLE
CircleCI config always shows success while there are test fails 

### ISSUE THREAD

**Issue by erwagasore** [pindo-io/pindo#43]
<img width="1045" alt="screen shot 2019-01-09 at 10 54 49" src="https://user-images.githubusercontent.com/1290048/50887941-216dac00-13fd-11e9-8644-9252b4313030.png">

**Comment by kenessajr** [comment]
I add `from app.sms.v1 import v1 as sms_v1  # NOQA` for skipping `FLAKE8` linting.
