### ISSUE TITLE
Create routes for telco services

### ISSUE THREAD

**Issue by erwagasore** [pindo-io/pindo#49]
Currently, there is no support for creating `services` using HTTP routes.

There are two paths we can take for this.
1. Combine them withing `telcos` blueprint `http://api.pindo.io/telcos/1/services/` or
2. Create its own independent blueprint `http://api.pindo.io/services/`

**Comment by kenessajr** [comment]
I think combining with `telcos` blueprint will be ideal as they share a lot in common.
