### ISSUE TITLE
Assertion error on showing remain one sms.

### ISSUE THREAD

**Issue by kenessajr** [pindo-io/pindo#54]
TestCase snippet 

```python
        # should show the remaining one sms
        resp = self.client.get(
            url_for('sms_v1.list'), headers=super_credentials, content_type='application/json')
        assert resp.status_code == 200
        assert len(resp.get_json()['sms']) == 0
```

<img width="721" alt="screen shot 2019-02-13 at 09 05 26" src="https://user-images.githubusercontent.com/5709541/52693200-bcaeef80-2f6e-11e9-8209-44d526e94e58.png">

**Comment by erwagasore** [comment]
@kenessajr this is a test fail you need to solve

**Comment by kenessajr** [comment]
The comment is saying should show the remaining one SMS, means that 
```python
assert len(resp.get_json()['sms']) == 1
```

**Comment by erwagasore** [comment]
Sometimes the comment is the ones which are not up to date.
I would advise you to go through the entire `test_sms.py` from the top. count SMS created and count those deleted. This will give you clarity of the remaining `sms`

**Comment by kenessajr** [comment]
Ok, nice. I think it will be better to also updated comment in the feature to not have these misunderstandings. 
Thanks

**Comment by erwagasore** [comment]
This was a miss from my part. It may happen again but I will do my best. 
On your side also you need to investigate what exactly is happening since you are able to do so before raising an issue or question.

**Comment by erwagasore** [comment]
Thank you for noticing it thought 🥇

**Comment by erwagasore** [comment]
I just checked the tests. The expected behaviour is that the list of sms should be `1`

**Comment by kenessajr** [comment]
Perfect!
