### ISSUE TITLE
User balance route is not getting the right user wallet

### ISSUE THREAD

**Issue by erwagasore** [pindo-io/pindo#57]
```python
@users.route('/<int:id>/balance', methods=['GET'])
@token.login_required
@requires(READ, User)
def balance(id):
    wallet = Wallet.get_wallet(id)
    payload = wallet.export_data()
    payload.update({'self_url': wallet.get_url()})
    return APIResult(payload)
```

This route doesn't get the wallet for this user. @kenessajr what was the logic behind this?
After correction we need extensive test to cover all potential cases

**Comment by kenessajr** [comment]
This route get the right user blance, we have `@staticmethod` called `get_wallet` on wallet model you can parse the `user_id` and get the wallet balance. 

```python
    @staticmethod
    def get_wallet(account_id):
        return Wallet.query.filter_by(account_id=account_id).first()
```

<img width="853" alt="Screen Shot 2019-04-09 at 17 03 34" src="https://user-images.githubusercontent.com/5709541/55811453-71860880-5ae9-11e9-8a3a-98634675c976.png">
