### ISSUE TITLE
template email not loading stylesheet.

### ISSUE THREAD

**Issue by kenessajr** [pindo-io/pindo#67]
<img width="1350" alt="Screen Shot 2019-04-16 at 16 14 32" src="https://user-images.githubusercontent.com/5709541/56217106-eebdfa00-6062-11e9-94a4-43befa4371f2.png">

**Comment by erwagasore** [comment]
Some people receive an email with a working template but others don't.
We need to investigate in depth this issue by trying it on different browsers and using different email clients. Email is one of our direct interfaces to clients we need to make sure that we are well represented.
