### ISSUE TITLE
Make username first letter uppercase!

### ISSUE THREAD

**Issue by kenessajr** [pindo-io/pindo#70]
Make first username upper case letter.

<img width="659" alt="Screen Shot 2019-04-22 at 16 19 24" src="https://user-images.githubusercontent.com/5709541/56504926-6fc13980-651a-11e9-855e-ecf0b2ef4a8f.png">

**Comment by erwagasore** [comment]
Username is different from names.

**Comment by kenessajr** [comment]
Ok, ok.

**Comment by erwagasore** [comment]
Usernames are meant to remain as they are. In the future, we will prompt users to fill their profiles where we gather their––names.
