### ISSUE TITLE
Check account balance

### ISSUE THREAD

**Issue by erwagasore** [pindo-io/pindo#75]
Provide account balance API endpoint for each customer to be able to preview account status

**Comment by erwagasore** [comment]
Once the endpoint is available we proceed on placing it within CLI client

**Comment by kenessajr** [comment]
We already have an endpoint `users/<int:id>/balance`, for achieving this with the `CLI` we need an endpoint like `users/balance` where we get the `user_id` through the current login session and get the wallet balance.

**Comment by erwagasore** [comment]
I just figured that we actually have two endpoints which all give the same details.
e.g. I can now access my account balance via `api.pindo.io/users/id/balance` but also `api.pindo.io/wallet/id`. But both `ids` are not the same. If an account id is `10` then the wallet endpoint would be pointing to `9` this is due to the fact that superuser doesn't have a wallet thus `-1` on the wallet.

**Comment by kenessajr** [comment]
Hey, @erwagasore this issue has been fixed right with this `pr` https://github.com/pindo-io/pindo/pull/77.  Confirm if yes, I will close it. 
Thanks.

**Comment by erwagasore** [comment]
Yeah. It is done.
